FROM node:22-alpine

WORKDIR /app

# Install dependencies
COPY frontend/package*.json ./
RUN npm install

# Copy the frontend code
COPY frontend/ ./

# Start the development server
CMD ["npm", "run", "dev"]